huh:
  encore:
    entries:
      - { name: contao-no-ui-slider-bundle, file: "vendor/heimrichhannot/contao-no-ui-slider-bundle/src/Resources/assets/js/contao-no-ui-slider-bundle.js"}
    legacy:
      js:
        - contao-no-ui-slider-bundle